/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package es.orange.inventory.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ReservedItems extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7620696928131879479L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReservedItems\",\"namespace\":\"es.orange.inventory.model\",\"fields\":[{\"name\":\"clientId\",\"type\":\"string\"},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Item\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ReservedItems> ENCODER =
      new BinaryMessageEncoder<ReservedItems>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReservedItems> DECODER =
      new BinaryMessageDecoder<ReservedItems>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ReservedItems> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ReservedItems> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ReservedItems> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ReservedItems>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ReservedItems to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ReservedItems from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ReservedItems instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ReservedItems fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence clientId;
  @Deprecated public java.util.List<es.orange.inventory.model.Item> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReservedItems() {}

  /**
   * All-args constructor.
   * @param clientId The new value for clientId
   * @param items The new value for items
   */
  public ReservedItems(java.lang.CharSequence clientId, java.util.List<es.orange.inventory.model.Item> items) {
    this.clientId = clientId;
    this.items = items;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return clientId;
    case 1: return items;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: clientId = (java.lang.CharSequence)value$; break;
    case 1: items = (java.util.List<es.orange.inventory.model.Item>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'clientId' field.
   * @return The value of the 'clientId' field.
   */
  public java.lang.CharSequence getClientId() {
    return clientId;
  }


  /**
   * Sets the value of the 'clientId' field.
   * @param value the value to set.
   */
  public void setClientId(java.lang.CharSequence value) {
    this.clientId = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<es.orange.inventory.model.Item> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<es.orange.inventory.model.Item> value) {
    this.items = value;
  }

  /**
   * Creates a new ReservedItems RecordBuilder.
   * @return A new ReservedItems RecordBuilder
   */
  public static es.orange.inventory.model.ReservedItems.Builder newBuilder() {
    return new es.orange.inventory.model.ReservedItems.Builder();
  }

  /**
   * Creates a new ReservedItems RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReservedItems RecordBuilder
   */
  public static es.orange.inventory.model.ReservedItems.Builder newBuilder(es.orange.inventory.model.ReservedItems.Builder other) {
    if (other == null) {
      return new es.orange.inventory.model.ReservedItems.Builder();
    } else {
      return new es.orange.inventory.model.ReservedItems.Builder(other);
    }
  }

  /**
   * Creates a new ReservedItems RecordBuilder by copying an existing ReservedItems instance.
   * @param other The existing instance to copy.
   * @return A new ReservedItems RecordBuilder
   */
  public static es.orange.inventory.model.ReservedItems.Builder newBuilder(es.orange.inventory.model.ReservedItems other) {
    if (other == null) {
      return new es.orange.inventory.model.ReservedItems.Builder();
    } else {
      return new es.orange.inventory.model.ReservedItems.Builder(other);
    }
  }

  /**
   * RecordBuilder for ReservedItems instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReservedItems>
    implements org.apache.avro.data.RecordBuilder<ReservedItems> {

    private java.lang.CharSequence clientId;
    private java.util.List<es.orange.inventory.model.Item> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(es.orange.inventory.model.ReservedItems.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ReservedItems instance
     * @param other The existing instance to copy.
     */
    private Builder(es.orange.inventory.model.ReservedItems other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'clientId' field.
      * @return The value.
      */
    public java.lang.CharSequence getClientId() {
      return clientId;
    }


    /**
      * Sets the value of the 'clientId' field.
      * @param value The value of 'clientId'.
      * @return This builder.
      */
    public es.orange.inventory.model.ReservedItems.Builder setClientId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.clientId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'clientId' field has been set.
      * @return True if the 'clientId' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'clientId' field.
      * @return This builder.
      */
    public es.orange.inventory.model.ReservedItems.Builder clearClientId() {
      clientId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<es.orange.inventory.model.Item> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public es.orange.inventory.model.ReservedItems.Builder setItems(java.util.List<es.orange.inventory.model.Item> value) {
      validate(fields()[1], value);
      this.items = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public es.orange.inventory.model.ReservedItems.Builder clearItems() {
      items = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReservedItems build() {
      try {
        ReservedItems record = new ReservedItems();
        record.clientId = fieldSetFlags()[0] ? this.clientId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.items = fieldSetFlags()[1] ? this.items : (java.util.List<es.orange.inventory.model.Item>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReservedItems>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReservedItems>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReservedItems>
    READER$ = (org.apache.avro.io.DatumReader<ReservedItems>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.clientId);

    long size0 = this.items.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (es.orange.inventory.model.Item e0: this.items) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.clientId = in.readString(this.clientId instanceof Utf8 ? (Utf8)this.clientId : null);

      long size0 = in.readArrayStart();
      java.util.List<es.orange.inventory.model.Item> a0 = this.items;
      if (a0 == null) {
        a0 = new SpecificData.Array<es.orange.inventory.model.Item>((int)size0, SCHEMA$.getField("items").schema());
        this.items = a0;
      } else a0.clear();
      SpecificData.Array<es.orange.inventory.model.Item> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<es.orange.inventory.model.Item>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          es.orange.inventory.model.Item e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new es.orange.inventory.model.Item();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.clientId = in.readString(this.clientId instanceof Utf8 ? (Utf8)this.clientId : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<es.orange.inventory.model.Item> a0 = this.items;
          if (a0 == null) {
            a0 = new SpecificData.Array<es.orange.inventory.model.Item>((int)size0, SCHEMA$.getField("items").schema());
            this.items = a0;
          } else a0.clear();
          SpecificData.Array<es.orange.inventory.model.Item> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<es.orange.inventory.model.Item>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              es.orange.inventory.model.Item e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new es.orange.inventory.model.Item();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










